name: FastPlayerHP
description: Show player health above head with an invisible armor stand.
version: '${version}'

main: cn.brocraft.fastPlayerHP.FastPlayerHP
api-version: '1.21'
load: POSTWORLD
softdepend: [ ProtocolLib ]

authors: [ TIQS ]
website: Distance.icu

commands:
  fphp:
    description: FastPlayerHP admin command
    usage: /fphp <reload|toggle|mode|render>
    permission: fastplayerhp.admin

permissions:
  fastplayerhp.admin:
    description: Allows using FastPlayerHP admin commands.
    default: op
